"""fix_auth_schema

Revision ID: 4d45c786fb18
Revises: bf729ede8c50
Create Date: 2026-05-01 23:32:41.053350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d45c786fb18'
down_revision: Union[str, Sequence[str], None] = 'bf729ede8c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_sources')
    op.drop_index(op.f('idx_business_owner'), table_name='business_entities')
    op.drop_table('business_entities')
    op.drop_table('evidence_records')
    op.drop_index(op.f('idx_audit_actor'), table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.add_column('auth_sessions', sa.Column('refresh_token_hash', sa.Text(), nullable=False))
    op.add_column('auth_sessions', sa.Column('status', sa.Text(), server_default=sa.text("'ACTIVE'"), nullable=False))
    op.drop_index(op.f('idx_auth_user'), table_name='auth_sessions')
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('idx_ca_assign_consent'), table_name='ca_assignments')
    op.drop_index(op.f('idx_ca_assign_filing'), table_name='ca_assignments')
    op.drop_index(op.f('idx_ca_assign_user'), table_name='ca_assignments')
    op.create_index(op.f('ix_ca_assignments_ca_user_id'), 'ca_assignments', ['ca_user_id'], unique=False)
    op.create_index(op.f('ix_ca_assignments_consent_id'), 'ca_assignments', ['consent_id'], unique=False)
    op.create_index(op.f('ix_ca_assignments_filing_id'), 'ca_assignments', ['filing_id'], unique=False)
    op.create_foreign_key(None, 'ca_assignments', 'filing_cases', ['filing_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_compliance_flags_user_id'), table_name='compliance_flags')
    op.drop_index(op.f('idx_consent_user'), table_name='consent_artifacts')
    op.create_index(op.f('ix_consent_artifacts_user_id'), 'consent_artifacts', ['user_id'], unique=False)
    op.drop_index(op.f('idx_consent_audit_actor'), table_name='consent_audit_logs')
    op.drop_index(op.f('idx_consent_audit_consent'), table_name='consent_audit_logs')
    op.create_index(op.f('ix_consent_audit_logs_actor_id'), 'consent_audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_consent_audit_logs_consent_id'), 'consent_audit_logs', ['consent_id'], unique=False)
    op.alter_column('submission_records', 'ack_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_submission_filing'), table_name='submission_records')
    op.create_index(op.f('ix_submission_records_filing_id'), 'submission_records', ['filing_id'], unique=False)
    op.create_foreign_key(None, 'submission_records', 'filing_cases', ['filing_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_confirmations', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_user_confirm_filing'), table_name='user_confirmations')
    op.drop_index(op.f('idx_user_confirm_user'), table_name='user_confirmations')
    op.create_index(op.f('ix_user_confirmations_filing_id'), 'user_confirmations', ['filing_id'], unique=False)
    op.create_foreign_key(None, 'user_confirmations', 'filing_cases', ['filing_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_credentials', sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('idx_credentials_provider'), table_name='user_credentials')
    op.drop_index(op.f('idx_credentials_user'), table_name='user_credentials')
    op.create_index(op.f('ix_user_credentials_user_id'), 'user_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_credentials_user_id'), table_name='user_credentials')
    op.create_index(op.f('idx_credentials_user'), 'user_credentials', ['user_id'], unique=False)
    op.create_index(op.f('idx_credentials_provider'), 'user_credentials', ['auth_provider'], unique=False)
    op.drop_column('user_credentials', 'last_failed_login_at')
    op.drop_constraint(None, 'user_confirmations', type_='foreignkey')
    op.drop_index(op.f('ix_user_confirmations_filing_id'), table_name='user_confirmations')
    op.create_index(op.f('idx_user_confirm_user'), 'user_confirmations', ['confirmed_by'], unique=False)
    op.create_index(op.f('idx_user_confirm_filing'), 'user_confirmations', ['filing_id'], unique=False)
    op.alter_column('user_confirmations', 'ip_address',
               existing_type=sa.String(),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.drop_constraint(None, 'submission_records', type_='foreignkey')
    op.drop_index(op.f('ix_submission_records_filing_id'), table_name='submission_records')
    op.create_index(op.f('idx_submission_filing'), 'submission_records', ['filing_id'], unique=False)
    op.alter_column('submission_records', 'ack_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_consent_audit_logs_consent_id'), table_name='consent_audit_logs')
    op.drop_index(op.f('ix_consent_audit_logs_actor_id'), table_name='consent_audit_logs')
    op.create_index(op.f('idx_consent_audit_consent'), 'consent_audit_logs', ['consent_id'], unique=False)
    op.create_index(op.f('idx_consent_audit_actor'), 'consent_audit_logs', ['actor_id'], unique=False)
    op.drop_index(op.f('ix_consent_artifacts_user_id'), table_name='consent_artifacts')
    op.create_index(op.f('idx_consent_user'), 'consent_artifacts', ['user_id'], unique=False)
    op.create_index(op.f('ix_compliance_flags_user_id'), 'compliance_flags', ['user_id'], unique=False)
    op.drop_constraint(None, 'ca_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_ca_assignments_filing_id'), table_name='ca_assignments')
    op.drop_index(op.f('ix_ca_assignments_consent_id'), table_name='ca_assignments')
    op.drop_index(op.f('ix_ca_assignments_ca_user_id'), table_name='ca_assignments')
    op.create_index(op.f('idx_ca_assign_user'), 'ca_assignments', ['ca_user_id'], unique=False)
    op.create_index(op.f('idx_ca_assign_filing'), 'ca_assignments', ['filing_id'], unique=False)
    op.create_index(op.f('idx_ca_assign_consent'), 'ca_assignments', ['consent_id'], unique=False)
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.create_index(op.f('idx_auth_user'), 'auth_sessions', ['user_id'], unique=False)
    op.drop_column('auth_sessions', 'status')
    op.drop_column('auth_sessions', 'refresh_token_hash')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.create_index(op.f('idx_audit_actor'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('related_action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('storage_location', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('retention_expiry', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('evidence_records_pkey'))
    )
    op.create_table('business_entities',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('owner_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('gstin', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('msme_status', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('incorporation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('business_entities_owner_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('business_entities_pkey')),
    sa.UniqueConstraint('gstin', name=op.f('unique_gstin'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_business_owner'), 'business_entities', ['owner_user_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('reference_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retrieved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("source_type::text = ANY (ARRAY['AIS'::character varying, 'AA'::character varying, 'UPLOAD'::character varying]::text[])", name=op.f('check_source_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('data_sources_pkey'))
    )
    # ### end Alembic commands ###
