"""add last failed login at to user credentials

Revision ID: b7d21390483c
Revises: b7d21390483b
Create Date: 2026-02-21 11:46:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d21390483c'
down_revision: Union[str, None] = 'b7d21390483b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'last_failed_login_at')
    # ### end Alembic commands ###
